name: Build and Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and test
      run: |
        python setup.py sdist bdist_wheel
        python -m unittest discover

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          python setup.py sdist bdist_wheel
          python -m unittest discover

      - name: Set up Python for publishing
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Set version from tag
        run: |
          version=$(echo "${GITHUB_REF##refs/tags/}")
          echo "::set-env name=PACKAGE_VERSION::$version"

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install twine
          twine upload dist/*
